apiVersion: apps/v1
kind: Deployment

metadata:
  name: hello-minikube

spec:
  replicas: 2

  selector:
    matchLabels:
      app: hello-minikube

  template:
    metadata:
      labels:
        app: hello-minikube

    spec:
      containers:
        - name: hello-minikube
          image: y1g0ul/hello-minikube:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 32777
